# =================================================
# Global Config
# =================================================
spring:
  application:
    name: nexo-suite
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          bach_size: 30
          order_inserts: true
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 0

# =================================================
# Server Configuration
# =================================================
server:
  port: ${SERVER_PORT:5055}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

# =================================================
# Logging (Advanced Configuration)
# =================================================
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      springframework.web: INFO
      hibernate: WARN
      hibernate.orm.jdbc.bind: TRACE
      springdoc: DEBUG
    com:
      zaxxer:
        hikari: WARN
  pattern:
    console: "%d{hh:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/nexo-suite.log
    max-size: 10MB
    max-history: 7

# =================================================
# Specific Configuration by profile (Example)
# =================================================
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      maximum-pool-size: 20

# ================================================
# Spring
# ================================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha